plugins {
    id 'com.android.library'
}

android {
    namespace 'com.xprobe.rpc'
    compileSdk 36

    defaultConfig {
        minSdk 21
        targetSdk 36

        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

// 无任何第三方依赖：仅依赖 android.jar 与 JDK
dependencies {
}
